stages:
  create_folds_dataset:
    cmd: python3 src/data/create_folds_data.py --config=params.yaml
    deps:
      - src/create_folds_data.py
      - data/raw/airline_sentiment_analysis.csv
      - src/utils.py
    outs:
      - data/interim/data_folds.csv
      - data/interim/test.csv

  clean_dataset:
    cmd: python3 src/clean_data.py --config=params.yaml
    deps:
      - src/clean_data.py
      - data/interim/data_folds.csv
      - data/interim/test.csv
      - src/utils.py
    outs:
      - data/processed/data_clean.csv
      - data/processed/test_clean.csv

  train_and_evaluate:
    cmd: python3 src/features/train_and_evaluate.py --config=params.yaml
    deps:
      - src/train_and_evaluate.py
      - data/processed/data_clean.csv
      - data/processed/test_clean.csv
      - src/utils.py
    outs:
      - models/tfv_features.pkl

  predict:
    cmd:  python3 src/features/predict.py --config=params.yaml
    deps:
      - src/predict.py
      - models/tfv_features.pkl
      - data/processed/data_clean.csv
      - data/processed/test.csv
      - src/utils.py
    outs:
      - models/LogisticRegression_model.pkl
      - reports/params.json
      - reports/scores.json

  



