base:
  project: sentiment-analysis
  random_state: 42
  target_col: airline_sentiment

data_source:
  raw_data_path: data/raw/airline_sentiment_analysis.csv

cv_folds_dataset:
  folds_data_path: data/interim/data_folds.csv
  fold_num: 5
  test_data_path: data/processed/test.csv
  test_size: 0.13

clean_dataset:
  clean_data_path: data/interim/data_clean.csv

build_features:
  feature_data_path: data/interim/data_features.csv
  tfv_artifact_path: src/feature/tfv_features.pkl

estimators:
  LogisticRegression:
    params:
      C: 1.0
      l1_ratio: 0.4

model_dir: models

reports:
  params: reports/params.json
  scores: reports/scores.json
