base:
  project: sentiment-analysis
  random_state: 42
  target_col: airline_sentiment
  estimator: LogisticRegression
  vectorizer: TfidfVectorizer
  metrics: [accuracy, f1, roc_auc, log_loss]

data_source:
  raw_data_path: data/raw/airline_sentiment_analysis.csv

split_dataset:
  folds_data_path: data/interim/data_folds.csv
  fold_num: 5
  test_data_path: data/interim/test.csv
  test_size: 0.13

clean_dataset:
  clean_folds_path: data/processed/data_clean.csv
  clean_test_path: data/processed/test_clean.csv
  
feature_generator:
  TfidfVectorizer:
    vectorizer_path: models/tfidf_vectorizer.pkl
    params:
      min_df: 3
      max_features: None
      strip_accents: unicode
      analyzer: word
      token_pattern: r"\w{1,}"
      ngram_range: (1, 3)
      use_idf: 1
      smooth_idf: 1
      sublinear_tf: 1
      stop_words: english
  CountVectorizer:
    vectorizer_path: models/count_vectorizer.pkl
    params:
      max_features: 1000
      ngram_range: (1, 2)

estimators:
  LogisticRegression:
    model_path: models/logistic_regression.pkl
    params:
      C: 1.0
      class_weight: null
      dual: false
      fit_intercept: true
      intercept_scaling: 1
      l1_ratio: null
      max_iter: 100
      multi_class: auto
      n_jobs: null
      penalty: l2
      random_state: 42
      solver: lbfgs
      tol: 0.0001
      verbose: 0
      warm_start: false
  RandomForestClassifier:
    model_path: models/random_forest.pkl
    params:
      bootstrap: true
      ccp_alpha: 0.0
      class_weight: null
      criterion: gini
      max_depth: null
      max_features: auto
      max_leaf_nodes: null
      max_samples: null
      min_impurity_decrease: 0.0
      min_impurity_split: null
      min_samples_leaf: 1
      min_samples_split: 2
      min_weight_fraction_leaf: 0.0
      n_estimators: 100
      n_jobs: null
      oob_score: false
      random_state: 42
      verbose: 0
      warm_start: false
  XGBClassifier:
    model_path: models/xgboost.pkl
    params:
      base_score: 0.5
      booster: gbtree
      colsample_bylevel: 1
      colsample_bynode: 1
      colsample_bytree: 1
      gamma: 0
      gpu_id: -1
      importance_type: gain
      interaction_constraints: ''
      learning_rate: 0.300000012
      max_delta_step: 0
      max_depth: 6
      min_child_weight: 1
      missing: nan
      monotone_constraints: '()'
      n_estimators: 100
      n_jobs: 0
      num_parallel_tree: 1
      random_state: 42
      reg_alpha: 0
      reg_lambda: 1
      scale_pos_weight: 1
      subsample: 1
      tree_method: exact
      validate_parameters: 1
      verbosity: null
  MultinomialNB:
    model_path: models/multinomial_nb.pkl
    params:
      alpha: 1.0
      class_prior: null
      fit_prior: true

model_dir: models

reports:
  params: reports/params.json
  scores_cv: reports/scores_cv.json
  scores_test: reports/scores_test.json
  